[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
crypto_ticket = "8f8WcT97fbiKZyFet48yQVH8jfTh2AWkXbpRjqzXRng9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
